#This is a comment
#
CC = gcc
CFLAGS = -Wall

OBJ = linked_list.o use_linked_list.o

all : use_linked_list

use_linked_list : linked_list.o use_linked_list.o
  gcc -Wall -o use_linked_list linked_list.o use_linked_list.o

use_linked_list .o: linked_list.h use_linked_list.c

linked_list .o: linked_list .h linked_list .c

clean:
  rm -f use_linked_list *.o *.exe
