#JTSK-320112
#Problem a3.p1.c
#Jonathan Rittmayer
#jo.rittmayer@jacobs-university.de

#From professor Lipskoch's slides
CC = gcc
CFLAGS = -Wall

OBJ = linked_list.o use_linked_list.o

all: use_linked_list

#Filled out professor's slides examples
use_linked_list: linked_list.o use_linked_list.o
	gcc -Wall -o use_linked_list linked_list.o use_linked_list.o

use_linked_list.o: linked_list.h use_linked_list.c

linked_list.o: linked_list.h linked_list.c

clean:
	rm -f use_linked_list *.o
